config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/ibergrid-perf:
      branch: main
      repo: https://github.com/EOSC-synergy/ibergrid-perf
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.0.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/EOSC-synergy/ibergrid-perf git:
        commands:
        - /usr/bin/env sh .sqa/script.beady-apricot-tapir.sh
        container: qc.acc_stuffy-vermilion-echidna
  QC.Doc:
    repos:
      github.com/EOSC-synergy/ibergrid-perf find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.frumpy-red-squirt.sh
        container: qc.doc_snappy-copper-hyena
      github.com/EOSC-synergy/ibergrid-perf git:
        commands:
        - /usr/bin/env sh .sqa/script.whiny-chocolate-anteater.sh
        container: qc.doc_geeky-tomato-sheepdog
  QC.Lic:
    repos:
      github.com/EOSC-synergy/ibergrid-perf licensee:
        commands:
        - /usr/bin/env sh .sqa/script.homely-ochre-gopher.sh
        container: qc.lic_messy-ecru-camel
  QC.Ver:
    repos:
      github.com/EOSC-synergy/ibergrid-perf get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.beady-vermilion-hyrax.sh
        container: qc.ver_chummy-tan-albatross
timeout: 5400
