config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.11
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/eosc-synergy/ibergrid-perf:
      branch: main
      repo: https://github.com/eosc-synergy/ibergrid-perf
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/eosc-synergy/ibergrid-perf git:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-olive-akita.sh
        container: qc.acc_frumpy-flax-skunk
  QC.Doc:
    repos:
      github.com/eosc-synergy/ibergrid-perf find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-magnolia-forest.sh
        container: qc.doc_skanky-peach-alligator
      github.com/eosc-synergy/ibergrid-perf git:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-vermilion-iguana.sh
        container: qc.doc_clammy-periwinkle-moorhen
      github.com/eosc-synergy/ibergrid-perf markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-russet-markhor.sh
        container: qc.doc_pokey-eggplant-yak
      github.com/eosc-synergy/ibergrid-perf restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.frumpy-wisteria-catfish.sh
        container: qc.doc_lanky-green-olm
  QC.Lic:
    repos:
      github.com/eosc-synergy/ibergrid-perf licensee:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-amethyst-mammoth.sh
        container: qc.lic_chewy-cobalt-crab
  QC.Met:
    repos:
      github.com/eosc-synergy/ibergrid-perf validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.shabby-lavender-jackal.sh
        container: qc.met_stinky-platinum-meerkat
  QC.Sec:
    repos:
      github.com/eosc-synergy/ibergrid-perf bandit:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-lime-moorhen.sh
        container: qc.sec_cozy-cyan-fly
  QC.Sty:
    repos:
      github.com/eosc-synergy/ibergrid-perf flake8:
        commands:
        - /usr/bin/env sh .sqa/script.gummy-yellow-husky.sh
        container: qc.sty_jumpy-saffron-raccoon
      github.com/eosc-synergy/ibergrid-perf hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-persimmon-urchin.sh
        container: qc.sty_pokey-firebrick-drever
      github.com/eosc-synergy/ibergrid-perf jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-cream-ray.sh
        container: qc.sty_shaggy-emerald-dragonfly
  QC.Ver:
    repos:
      github.com/eosc-synergy/ibergrid-perf get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-cerulean-seahorse.sh
        container: qc.ver_jumpy-jade-gorilla
timeout: 5400
